version: '3'

services:
  mysql:
    image: mysql8.0.17
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iopasd753951
      - MYSQL_DATABASE='herren_hm'
      - MYSQL_USER='root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
    - "8080:8080"
    depends_on:
      - mysql
