version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ../volumes-mysql/mysql/:/var/lib/mysql/
    environment:
      - DB_ROOT_PASSWORD=iopasd753951
      - DB_DATABASE=herren_hm
      - DB_USER=root
      - DB_PASSWORD=iopasd753951
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 127.0.0.1:8080
    volumes:
    - ./app:/app
    ports:
    - "8080:8080"
    depends_on:
      - mysql
